--!strict
--!optimize 2
--!native

local StackModifierTypes = require(script.stackModifier)

export type Release = StackModifierTypes.Release
export type SpeedModifierMode = StackModifierTypes.SpeedModifierMode
export type SpeedModifierOptions = StackModifierTypes.SpeedModifierOptions
export type StackModifier = StackModifierTypes.StackModifier
export type StackModifierImpl = StackModifierTypes.StackModifierImpl
export type StackModifierConfig = StackModifierTypes.StackModifierConfig
export type StackModifierEntry = StackModifierTypes.StackModifierEntry

return {}
